# Generated by Django 5.1.7 on 2025-03-23 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_user_conversation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodpreference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='foodpreference',
            name='rank',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('ChatBot', 'ChatBot'), ('ChatgptA', 'ChatGPT A'), ('ChatgptB', 'ChatGPT B')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='foodpreference',
            unique_together={('conversation', 'rank')},
        ),
    ]
